### ISSUE TITLE
AttributeError: module 'sparse_diffusion.utils' has no attribute 'densify_noisy_data'

### ISSUE THREAD

**Issue by W-ZN** [qym7/SparseDiff#1]
When I run the command ‘python3 main.py general.name=test’, the console displays an error message:

> Error executing job with overrides: ['general.name=test']
Traceback (most recent call last):
  File "/Users/wzn/code/SparseDiff/sparse_diffusion/main.py", line 121, in main
    dataset_infos.compute_input_dims(
  File "/Users/wzn/code/SparseDiff/sparse_diffusion/datasets/abstract_dataset.py", line 204, in compute_input_dims
    ex_extra_feat = extra_features(example_data)
  File "/Users/wzn/code/SparseDiff/sparse_diffusion/diffusion/extra_features.py", line 52, in __call__
    noisy_data = utils.densify_noisy_data(sparse_noisy_data)
AttributeError: module 'sparse_diffusion.utils' has no attribute 'densify_noisy_data'

And I didn't find that method in utils.py. 
How should I handle it to ensure that the code can run properly?

**Comment by qym7** [comment]
Sorry, this function has been accidentally deleted and it has been added.
Thanks for pointing out this issue.

**Comment by W-ZN** [comment]
> Sorry, this function has been accidentally deleted and it has been added. Thanks for pointing out this issue.

thank you for your reply! I'll try to reuse the code to test.
